version: "3.8"

services:
  app:
    build: .
    container_name: react-vite-app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npm install -g pnpm &&
        pnpm install &&
        pnpm run build &&
        pnpm preview"
    restart: unless-stopped
